# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ros_pb2 as ros__pb2


class rosoutStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Publish = channel.unary_unary(
                '/ros.rosout/Publish',
                request_serializer=ros__pb2.rosgraph_msgs.Log.SerializeToString,
                response_deserializer=ros__pb2.Empty.FromString,
                )
        self.Subscribe = channel.unary_stream(
                '/ros.rosout/Subscribe',
                request_serializer=ros__pb2.Empty.SerializeToString,
                response_deserializer=ros__pb2.rosgraph_msgs.Log.FromString,
                )


class rosoutServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Publish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_rosoutServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=ros__pb2.rosgraph_msgs.Log.FromString,
                    response_serializer=ros__pb2.Empty.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=ros__pb2.Empty.FromString,
                    response_serializer=ros__pb2.rosgraph_msgs.Log.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ros.rosout', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class rosout(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ros.rosout/Publish',
            ros__pb2.rosgraph_msgs.Log.SerializeToString,
            ros__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ros.rosout/Subscribe',
            ros__pb2.Empty.SerializeToString,
            ros__pb2.rosgraph_msgs.Log.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class rosout_aggStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Publish = channel.unary_unary(
                '/ros.rosout_agg/Publish',
                request_serializer=ros__pb2.rosgraph_msgs.Log.SerializeToString,
                response_deserializer=ros__pb2.Empty.FromString,
                )
        self.Subscribe = channel.unary_stream(
                '/ros.rosout_agg/Subscribe',
                request_serializer=ros__pb2.Empty.SerializeToString,
                response_deserializer=ros__pb2.rosgraph_msgs.Log.FromString,
                )


class rosout_aggServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Publish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_rosout_aggServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=ros__pb2.rosgraph_msgs.Log.FromString,
                    response_serializer=ros__pb2.Empty.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=ros__pb2.Empty.FromString,
                    response_serializer=ros__pb2.rosgraph_msgs.Log.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ros.rosout_agg', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class rosout_agg(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ros.rosout_agg/Publish',
            ros__pb2.rosgraph_msgs.Log.SerializeToString,
            ros__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ros.rosout_agg/Subscribe',
            ros__pb2.Empty.SerializeToString,
            ros__pb2.rosgraph_msgs.Log.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class shapes_cancelStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Publish = channel.unary_unary(
                '/ros.shapes_cancel/Publish',
                request_serializer=ros__pb2.actionlib_msgs.GoalID.SerializeToString,
                response_deserializer=ros__pb2.Empty.FromString,
                )
        self.Subscribe = channel.unary_stream(
                '/ros.shapes_cancel/Subscribe',
                request_serializer=ros__pb2.Empty.SerializeToString,
                response_deserializer=ros__pb2.actionlib_msgs.GoalID.FromString,
                )


class shapes_cancelServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Publish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_shapes_cancelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=ros__pb2.actionlib_msgs.GoalID.FromString,
                    response_serializer=ros__pb2.Empty.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=ros__pb2.Empty.FromString,
                    response_serializer=ros__pb2.actionlib_msgs.GoalID.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ros.shapes_cancel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class shapes_cancel(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ros.shapes_cancel/Publish',
            ros__pb2.actionlib_msgs.GoalID.SerializeToString,
            ros__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ros.shapes_cancel/Subscribe',
            ros__pb2.Empty.SerializeToString,
            ros__pb2.actionlib_msgs.GoalID.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class shapes_feedbackStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Publish = channel.unary_unary(
                '/ros.shapes_feedback/Publish',
                request_serializer=ros__pb2.turtle_actionlib.ShapeActionFeedback.SerializeToString,
                response_deserializer=ros__pb2.Empty.FromString,
                )
        self.Subscribe = channel.unary_stream(
                '/ros.shapes_feedback/Subscribe',
                request_serializer=ros__pb2.Empty.SerializeToString,
                response_deserializer=ros__pb2.turtle_actionlib.ShapeActionFeedback.FromString,
                )


class shapes_feedbackServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Publish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_shapes_feedbackServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=ros__pb2.turtle_actionlib.ShapeActionFeedback.FromString,
                    response_serializer=ros__pb2.Empty.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=ros__pb2.Empty.FromString,
                    response_serializer=ros__pb2.turtle_actionlib.ShapeActionFeedback.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ros.shapes_feedback', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class shapes_feedback(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ros.shapes_feedback/Publish',
            ros__pb2.turtle_actionlib.ShapeActionFeedback.SerializeToString,
            ros__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ros.shapes_feedback/Subscribe',
            ros__pb2.Empty.SerializeToString,
            ros__pb2.turtle_actionlib.ShapeActionFeedback.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class shapes_goalStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Publish = channel.unary_unary(
                '/ros.shapes_goal/Publish',
                request_serializer=ros__pb2.turtle_actionlib.ShapeActionGoal.SerializeToString,
                response_deserializer=ros__pb2.Empty.FromString,
                )
        self.Subscribe = channel.unary_stream(
                '/ros.shapes_goal/Subscribe',
                request_serializer=ros__pb2.Empty.SerializeToString,
                response_deserializer=ros__pb2.turtle_actionlib.ShapeActionGoal.FromString,
                )


class shapes_goalServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Publish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_shapes_goalServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=ros__pb2.turtle_actionlib.ShapeActionGoal.FromString,
                    response_serializer=ros__pb2.Empty.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=ros__pb2.Empty.FromString,
                    response_serializer=ros__pb2.turtle_actionlib.ShapeActionGoal.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ros.shapes_goal', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class shapes_goal(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ros.shapes_goal/Publish',
            ros__pb2.turtle_actionlib.ShapeActionGoal.SerializeToString,
            ros__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ros.shapes_goal/Subscribe',
            ros__pb2.Empty.SerializeToString,
            ros__pb2.turtle_actionlib.ShapeActionGoal.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class shapes_resultStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Publish = channel.unary_unary(
                '/ros.shapes_result/Publish',
                request_serializer=ros__pb2.turtle_actionlib.ShapeActionResult.SerializeToString,
                response_deserializer=ros__pb2.Empty.FromString,
                )
        self.Subscribe = channel.unary_stream(
                '/ros.shapes_result/Subscribe',
                request_serializer=ros__pb2.Empty.SerializeToString,
                response_deserializer=ros__pb2.turtle_actionlib.ShapeActionResult.FromString,
                )


class shapes_resultServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Publish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_shapes_resultServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=ros__pb2.turtle_actionlib.ShapeActionResult.FromString,
                    response_serializer=ros__pb2.Empty.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=ros__pb2.Empty.FromString,
                    response_serializer=ros__pb2.turtle_actionlib.ShapeActionResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ros.shapes_result', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class shapes_result(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ros.shapes_result/Publish',
            ros__pb2.turtle_actionlib.ShapeActionResult.SerializeToString,
            ros__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ros.shapes_result/Subscribe',
            ros__pb2.Empty.SerializeToString,
            ros__pb2.turtle_actionlib.ShapeActionResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class shapes_statusStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Publish = channel.unary_unary(
                '/ros.shapes_status/Publish',
                request_serializer=ros__pb2.actionlib_msgs.GoalStatusArray.SerializeToString,
                response_deserializer=ros__pb2.Empty.FromString,
                )
        self.Subscribe = channel.unary_stream(
                '/ros.shapes_status/Subscribe',
                request_serializer=ros__pb2.Empty.SerializeToString,
                response_deserializer=ros__pb2.actionlib_msgs.GoalStatusArray.FromString,
                )


class shapes_statusServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Publish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_shapes_statusServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=ros__pb2.actionlib_msgs.GoalStatusArray.FromString,
                    response_serializer=ros__pb2.Empty.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=ros__pb2.Empty.FromString,
                    response_serializer=ros__pb2.actionlib_msgs.GoalStatusArray.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ros.shapes_status', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class shapes_status(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ros.shapes_status/Publish',
            ros__pb2.actionlib_msgs.GoalStatusArray.SerializeToString,
            ros__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ros.shapes_status/Subscribe',
            ros__pb2.Empty.SerializeToString,
            ros__pb2.actionlib_msgs.GoalStatusArray.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class turtle1_cmd_velStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Publish = channel.unary_unary(
                '/ros.turtle1_cmd_vel/Publish',
                request_serializer=ros__pb2.geometry_msgs.Twist.SerializeToString,
                response_deserializer=ros__pb2.Empty.FromString,
                )
        self.Subscribe = channel.unary_stream(
                '/ros.turtle1_cmd_vel/Subscribe',
                request_serializer=ros__pb2.Empty.SerializeToString,
                response_deserializer=ros__pb2.geometry_msgs.Twist.FromString,
                )


class turtle1_cmd_velServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Publish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_turtle1_cmd_velServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=ros__pb2.geometry_msgs.Twist.FromString,
                    response_serializer=ros__pb2.Empty.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=ros__pb2.Empty.FromString,
                    response_serializer=ros__pb2.geometry_msgs.Twist.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ros.turtle1_cmd_vel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class turtle1_cmd_vel(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ros.turtle1_cmd_vel/Publish',
            ros__pb2.geometry_msgs.Twist.SerializeToString,
            ros__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ros.turtle1_cmd_vel/Subscribe',
            ros__pb2.Empty.SerializeToString,
            ros__pb2.geometry_msgs.Twist.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class turtle1_color_sensorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Publish = channel.unary_unary(
                '/ros.turtle1_color_sensor/Publish',
                request_serializer=ros__pb2.turtlesim.Color.SerializeToString,
                response_deserializer=ros__pb2.Empty.FromString,
                )
        self.Subscribe = channel.unary_stream(
                '/ros.turtle1_color_sensor/Subscribe',
                request_serializer=ros__pb2.Empty.SerializeToString,
                response_deserializer=ros__pb2.turtlesim.Color.FromString,
                )


class turtle1_color_sensorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Publish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_turtle1_color_sensorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=ros__pb2.turtlesim.Color.FromString,
                    response_serializer=ros__pb2.Empty.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=ros__pb2.Empty.FromString,
                    response_serializer=ros__pb2.turtlesim.Color.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ros.turtle1_color_sensor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class turtle1_color_sensor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ros.turtle1_color_sensor/Publish',
            ros__pb2.turtlesim.Color.SerializeToString,
            ros__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ros.turtle1_color_sensor/Subscribe',
            ros__pb2.Empty.SerializeToString,
            ros__pb2.turtlesim.Color.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class turtle1_poseStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Publish = channel.unary_unary(
                '/ros.turtle1_pose/Publish',
                request_serializer=ros__pb2.turtlesim.Pose.SerializeToString,
                response_deserializer=ros__pb2.Empty.FromString,
                )
        self.Subscribe = channel.unary_stream(
                '/ros.turtle1_pose/Subscribe',
                request_serializer=ros__pb2.Empty.SerializeToString,
                response_deserializer=ros__pb2.turtlesim.Pose.FromString,
                )


class turtle1_poseServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Publish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_turtle1_poseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=ros__pb2.turtlesim.Pose.FromString,
                    response_serializer=ros__pb2.Empty.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=ros__pb2.Empty.FromString,
                    response_serializer=ros__pb2.turtlesim.Pose.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ros.turtle1_pose', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class turtle1_pose(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ros.turtle1_pose/Publish',
            ros__pb2.turtlesim.Pose.SerializeToString,
            ros__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ros.turtle1_pose/Subscribe',
            ros__pb2.Empty.SerializeToString,
            ros__pb2.turtlesim.Pose.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class clearStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Call = channel.unary_unary(
                '/ros.clear/Call',
                request_serializer=ros__pb2.std_srvs.EmptyRequest.SerializeToString,
                response_deserializer=ros__pb2.std_srvs.EmptyResponse.FromString,
                )


class clearServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Call(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_clearServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Call': grpc.unary_unary_rpc_method_handler(
                    servicer.Call,
                    request_deserializer=ros__pb2.std_srvs.EmptyRequest.FromString,
                    response_serializer=ros__pb2.std_srvs.EmptyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ros.clear', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class clear(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ros.clear/Call',
            ros__pb2.std_srvs.EmptyRequest.SerializeToString,
            ros__pb2.std_srvs.EmptyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class killStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Call = channel.unary_unary(
                '/ros.kill/Call',
                request_serializer=ros__pb2.turtlesim.KillRequest.SerializeToString,
                response_deserializer=ros__pb2.turtlesim.KillResponse.FromString,
                )


class killServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Call(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_killServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Call': grpc.unary_unary_rpc_method_handler(
                    servicer.Call,
                    request_deserializer=ros__pb2.turtlesim.KillRequest.FromString,
                    response_serializer=ros__pb2.turtlesim.KillResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ros.kill', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class kill(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ros.kill/Call',
            ros__pb2.turtlesim.KillRequest.SerializeToString,
            ros__pb2.turtlesim.KillResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class resetStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Call = channel.unary_unary(
                '/ros.reset/Call',
                request_serializer=ros__pb2.std_srvs.EmptyRequest.SerializeToString,
                response_deserializer=ros__pb2.std_srvs.EmptyResponse.FromString,
                )


class resetServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Call(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_resetServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Call': grpc.unary_unary_rpc_method_handler(
                    servicer.Call,
                    request_deserializer=ros__pb2.std_srvs.EmptyRequest.FromString,
                    response_serializer=ros__pb2.std_srvs.EmptyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ros.reset', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class reset(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ros.reset/Call',
            ros__pb2.std_srvs.EmptyRequest.SerializeToString,
            ros__pb2.std_srvs.EmptyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class rosout_get_loggersStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Call = channel.unary_unary(
                '/ros.rosout_get_loggers/Call',
                request_serializer=ros__pb2.roscpp.GetLoggersRequest.SerializeToString,
                response_deserializer=ros__pb2.roscpp.GetLoggersResponse.FromString,
                )


class rosout_get_loggersServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Call(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_rosout_get_loggersServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Call': grpc.unary_unary_rpc_method_handler(
                    servicer.Call,
                    request_deserializer=ros__pb2.roscpp.GetLoggersRequest.FromString,
                    response_serializer=ros__pb2.roscpp.GetLoggersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ros.rosout_get_loggers', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class rosout_get_loggers(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ros.rosout_get_loggers/Call',
            ros__pb2.roscpp.GetLoggersRequest.SerializeToString,
            ros__pb2.roscpp.GetLoggersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class rosout_set_logger_levelStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Call = channel.unary_unary(
                '/ros.rosout_set_logger_level/Call',
                request_serializer=ros__pb2.roscpp.SetLoggerLevelRequest.SerializeToString,
                response_deserializer=ros__pb2.roscpp.SetLoggerLevelResponse.FromString,
                )


class rosout_set_logger_levelServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Call(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_rosout_set_logger_levelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Call': grpc.unary_unary_rpc_method_handler(
                    servicer.Call,
                    request_deserializer=ros__pb2.roscpp.SetLoggerLevelRequest.FromString,
                    response_serializer=ros__pb2.roscpp.SetLoggerLevelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ros.rosout_set_logger_level', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class rosout_set_logger_level(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ros.rosout_set_logger_level/Call',
            ros__pb2.roscpp.SetLoggerLevelRequest.SerializeToString,
            ros__pb2.roscpp.SetLoggerLevelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class shapes_get_loggersStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Call = channel.unary_unary(
                '/ros.shapes_get_loggers/Call',
                request_serializer=ros__pb2.roscpp.GetLoggersRequest.SerializeToString,
                response_deserializer=ros__pb2.roscpp.GetLoggersResponse.FromString,
                )


class shapes_get_loggersServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Call(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_shapes_get_loggersServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Call': grpc.unary_unary_rpc_method_handler(
                    servicer.Call,
                    request_deserializer=ros__pb2.roscpp.GetLoggersRequest.FromString,
                    response_serializer=ros__pb2.roscpp.GetLoggersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ros.shapes_get_loggers', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class shapes_get_loggers(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ros.shapes_get_loggers/Call',
            ros__pb2.roscpp.GetLoggersRequest.SerializeToString,
            ros__pb2.roscpp.GetLoggersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class shapes_set_logger_levelStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Call = channel.unary_unary(
                '/ros.shapes_set_logger_level/Call',
                request_serializer=ros__pb2.roscpp.SetLoggerLevelRequest.SerializeToString,
                response_deserializer=ros__pb2.roscpp.SetLoggerLevelResponse.FromString,
                )


class shapes_set_logger_levelServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Call(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_shapes_set_logger_levelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Call': grpc.unary_unary_rpc_method_handler(
                    servicer.Call,
                    request_deserializer=ros__pb2.roscpp.SetLoggerLevelRequest.FromString,
                    response_serializer=ros__pb2.roscpp.SetLoggerLevelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ros.shapes_set_logger_level', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class shapes_set_logger_level(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ros.shapes_set_logger_level/Call',
            ros__pb2.roscpp.SetLoggerLevelRequest.SerializeToString,
            ros__pb2.roscpp.SetLoggerLevelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class sim_get_loggersStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Call = channel.unary_unary(
                '/ros.sim_get_loggers/Call',
                request_serializer=ros__pb2.roscpp.GetLoggersRequest.SerializeToString,
                response_deserializer=ros__pb2.roscpp.GetLoggersResponse.FromString,
                )


class sim_get_loggersServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Call(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_sim_get_loggersServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Call': grpc.unary_unary_rpc_method_handler(
                    servicer.Call,
                    request_deserializer=ros__pb2.roscpp.GetLoggersRequest.FromString,
                    response_serializer=ros__pb2.roscpp.GetLoggersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ros.sim_get_loggers', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class sim_get_loggers(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ros.sim_get_loggers/Call',
            ros__pb2.roscpp.GetLoggersRequest.SerializeToString,
            ros__pb2.roscpp.GetLoggersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class sim_set_logger_levelStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Call = channel.unary_unary(
                '/ros.sim_set_logger_level/Call',
                request_serializer=ros__pb2.roscpp.SetLoggerLevelRequest.SerializeToString,
                response_deserializer=ros__pb2.roscpp.SetLoggerLevelResponse.FromString,
                )


class sim_set_logger_levelServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Call(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_sim_set_logger_levelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Call': grpc.unary_unary_rpc_method_handler(
                    servicer.Call,
                    request_deserializer=ros__pb2.roscpp.SetLoggerLevelRequest.FromString,
                    response_serializer=ros__pb2.roscpp.SetLoggerLevelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ros.sim_set_logger_level', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class sim_set_logger_level(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ros.sim_set_logger_level/Call',
            ros__pb2.roscpp.SetLoggerLevelRequest.SerializeToString,
            ros__pb2.roscpp.SetLoggerLevelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class spawnStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Call = channel.unary_unary(
                '/ros.spawn/Call',
                request_serializer=ros__pb2.turtlesim.SpawnRequest.SerializeToString,
                response_deserializer=ros__pb2.turtlesim.SpawnResponse.FromString,
                )


class spawnServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Call(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_spawnServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Call': grpc.unary_unary_rpc_method_handler(
                    servicer.Call,
                    request_deserializer=ros__pb2.turtlesim.SpawnRequest.FromString,
                    response_serializer=ros__pb2.turtlesim.SpawnResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ros.spawn', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class spawn(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ros.spawn/Call',
            ros__pb2.turtlesim.SpawnRequest.SerializeToString,
            ros__pb2.turtlesim.SpawnResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class turtle1_set_penStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Call = channel.unary_unary(
                '/ros.turtle1_set_pen/Call',
                request_serializer=ros__pb2.turtlesim.SetPenRequest.SerializeToString,
                response_deserializer=ros__pb2.turtlesim.SetPenResponse.FromString,
                )


class turtle1_set_penServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Call(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_turtle1_set_penServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Call': grpc.unary_unary_rpc_method_handler(
                    servicer.Call,
                    request_deserializer=ros__pb2.turtlesim.SetPenRequest.FromString,
                    response_serializer=ros__pb2.turtlesim.SetPenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ros.turtle1_set_pen', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class turtle1_set_pen(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ros.turtle1_set_pen/Call',
            ros__pb2.turtlesim.SetPenRequest.SerializeToString,
            ros__pb2.turtlesim.SetPenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class turtle1_teleport_absoluteStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Call = channel.unary_unary(
                '/ros.turtle1_teleport_absolute/Call',
                request_serializer=ros__pb2.turtlesim.TeleportAbsoluteRequest.SerializeToString,
                response_deserializer=ros__pb2.turtlesim.TeleportAbsoluteResponse.FromString,
                )


class turtle1_teleport_absoluteServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Call(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_turtle1_teleport_absoluteServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Call': grpc.unary_unary_rpc_method_handler(
                    servicer.Call,
                    request_deserializer=ros__pb2.turtlesim.TeleportAbsoluteRequest.FromString,
                    response_serializer=ros__pb2.turtlesim.TeleportAbsoluteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ros.turtle1_teleport_absolute', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class turtle1_teleport_absolute(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ros.turtle1_teleport_absolute/Call',
            ros__pb2.turtlesim.TeleportAbsoluteRequest.SerializeToString,
            ros__pb2.turtlesim.TeleportAbsoluteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class turtle1_teleport_relativeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Call = channel.unary_unary(
                '/ros.turtle1_teleport_relative/Call',
                request_serializer=ros__pb2.turtlesim.TeleportRelativeRequest.SerializeToString,
                response_deserializer=ros__pb2.turtlesim.TeleportRelativeResponse.FromString,
                )


class turtle1_teleport_relativeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Call(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_turtle1_teleport_relativeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Call': grpc.unary_unary_rpc_method_handler(
                    servicer.Call,
                    request_deserializer=ros__pb2.turtlesim.TeleportRelativeRequest.FromString,
                    response_serializer=ros__pb2.turtlesim.TeleportRelativeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ros.turtle1_teleport_relative', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class turtle1_teleport_relative(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ros.turtle1_teleport_relative/Call',
            ros__pb2.turtlesim.TeleportRelativeRequest.SerializeToString,
            ros__pb2.turtlesim.TeleportRelativeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
