#!/bin/sh
cd "${0%/*}" # change the working dir to the one where the script is (scripts/)

FILE=./generated/grpc_server.py
if [ -f "$FILE" ]; then
    cd ./generated
    python3 grpc_server.py
    echo "$FILE exists."
else 
    echo "$FILE does not exist. Did you run 'roslaunch grpc_bridge_generator generate.launch'?"
fi
